version: 2
updates:
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: com.google.guava:guava
    update_types: ["version-update:semver-major"]
  - dependency-name: org.slf4j:slf4j-api
    update_types: ["version-update:semver-major"]
